name: Build

on:
  workflow_call:

jobs:
  cli:
    name: CLI

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        name: Checkout Code

      - uses: pnpm/action-setup@v6
        name: Install pnpm

        with:
          version: 11

      - uses: actions/setup-node@v6
        name: Setup Node.js

        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install
        name: Install Dependencies

      - run: pnpm build
        name: Build Package

      - run: node dist/index.js --help
        name: Test CLI Help

      - run: node dist/index.js --version
        name: Test CLI Version
